// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options,
  get,
  getAdminDashboardStats,
  getAdminUsers,
  getAdminOrders,
  getAdminDriverApplications,
  patchAdminUsersByIdRole,
  postAdminCleanup,
  postAuthLogin,
  postAuthRegister,
  postAuthRefresh,
  postAuthLogout,
  postAuthLogoutAll,
  getAuthMe,
  getUsers,
  postUsers,
  deleteUsersById,
  getUsersById,
  patchUsersById,
  getOrders,
  postOrders,
  getOrdersAvailable,
  deleteOrdersById,
  getOrdersById,
  patchOrdersById,
  getOrdersByIdApplications,
  getDriversByIdApplications,
  postDriverApplications,
  patchDriverApplicationsById,
  getRealtimeWebsocket,
  postRealtimeBroadcast,
  getRealtimeConnections,
  getRealtimeHealth,
} from '../sdk.gen';
import {
  queryOptions,
  infiniteQueryOptions,
  type InfiniteData,
  type UseMutationOptions,
} from '@tanstack/react-query';
import type {
  GetData,
  GetAdminDashboardStatsData,
  GetAdminUsersData,
  GetAdminUsersError,
  GetAdminUsersResponse,
  GetAdminOrdersData,
  GetAdminOrdersError,
  GetAdminOrdersResponse,
  GetAdminDriverApplicationsData,
  GetAdminDriverApplicationsError,
  GetAdminDriverApplicationsResponse,
  PatchAdminUsersByIdRoleData,
  PatchAdminUsersByIdRoleError,
  PatchAdminUsersByIdRoleResponse,
  PostAdminCleanupData,
  PostAdminCleanupError,
  PostAdminCleanupResponse,
  PostAuthLoginData,
  PostAuthLoginError,
  PostAuthLoginResponse,
  PostAuthRegisterData,
  PostAuthRegisterError,
  PostAuthRegisterResponse,
  PostAuthRefreshData,
  PostAuthRefreshError,
  PostAuthRefreshResponse,
  PostAuthLogoutData,
  PostAuthLogoutError,
  PostAuthLogoutResponse,
  PostAuthLogoutAllData,
  PostAuthLogoutAllError,
  PostAuthLogoutAllResponse,
  GetAuthMeData,
  GetUsersData,
  GetUsersError,
  GetUsersResponse,
  PostUsersData,
  PostUsersError,
  PostUsersResponse,
  DeleteUsersByIdData,
  DeleteUsersByIdError,
  DeleteUsersByIdResponse,
  GetUsersByIdData,
  PatchUsersByIdData,
  PatchUsersByIdError,
  PatchUsersByIdResponse,
  GetOrdersData,
  GetOrdersError,
  GetOrdersResponse,
  PostOrdersData,
  PostOrdersError,
  PostOrdersResponse,
  GetOrdersAvailableData,
  GetOrdersAvailableError,
  GetOrdersAvailableResponse,
  DeleteOrdersByIdData,
  DeleteOrdersByIdError,
  DeleteOrdersByIdResponse,
  GetOrdersByIdData,
  PatchOrdersByIdData,
  PatchOrdersByIdError,
  PatchOrdersByIdResponse,
  GetOrdersByIdApplicationsData,
  GetOrdersByIdApplicationsError,
  GetOrdersByIdApplicationsResponse,
  GetDriversByIdApplicationsData,
  GetDriversByIdApplicationsError,
  GetDriversByIdApplicationsResponse,
  PostDriverApplicationsData,
  PostDriverApplicationsError,
  PostDriverApplicationsResponse,
  PatchDriverApplicationsByIdData,
  PatchDriverApplicationsByIdError,
  PatchDriverApplicationsByIdResponse,
  GetRealtimeWebsocketData,
  PostRealtimeBroadcastData,
  PostRealtimeBroadcastError,
  PostRealtimeBroadcastResponse,
  GetRealtimeConnectionsData,
  GetRealtimeHealthData,
} from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getQueryKey = (options?: Options<GetData>) => createQueryKey('get', options);

/**
 * API health check and information
 * Returns comprehensive information about the Cargo API service including health status, environment details, and service availability. This endpoint serves as a global health check for monitoring systems worldwide and provides confirmation that the API is running and accessible.
 */
export const getOptions = (options?: Options<GetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await get({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getQueryKey(options),
  });
};

export const getAdminDashboardStatsQueryKey = (options?: Options<GetAdminDashboardStatsData>) =>
  createQueryKey('getAdminDashboardStats', options);

/**
 * Get admin dashboard statistics
 * Retrieves comprehensive statistics for the admin dashboard including user counts, order statistics, and application metrics. This endpoint provides a high-level overview of the system's current state.
 */
export const getAdminDashboardStatsOptions = (options?: Options<GetAdminDashboardStatsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAdminDashboardStats({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAdminDashboardStatsQueryKey(options),
  });
};

export const getAdminUsersQueryKey = (options?: Options<GetAdminUsersData>) =>
  createQueryKey('getAdminUsers', options);

/**
 * Get all users with filtering and sorting (admin only)
 * Retrieves a paginated list of all users in the system with comprehensive filtering and sorting capabilities. This endpoint is restricted to admin users and provides detailed user information including creation dates and subscription status. Supports filtering by role, location, subscription status, and search across user information.
 */
export const getAdminUsersOptions = (options?: Options<GetAdminUsersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAdminUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAdminUsersQueryKey(options),
  });
};

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = queryKey[0];
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getAdminUsersInfiniteQueryKey = (
  options?: Options<GetAdminUsersData>
): QueryKey<Options<GetAdminUsersData>> => createQueryKey('getAdminUsers', options, true);

/**
 * Get all users with filtering and sorting (admin only)
 * Retrieves a paginated list of all users in the system with comprehensive filtering and sorting capabilities. This endpoint is restricted to admin users and provides detailed user information including creation dates and subscription status. Supports filtering by role, location, subscription status, and search across user information.
 */
export const getAdminUsersInfiniteOptions = (options?: Options<GetAdminUsersData>) => {
  return infiniteQueryOptions<
    GetAdminUsersResponse,
    GetAdminUsersError,
    InfiniteData<GetAdminUsersResponse>,
    QueryKey<Options<GetAdminUsersData>>,
    number | Pick<QueryKey<Options<GetAdminUsersData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetAdminUsersData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getAdminUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getAdminUsersInfiniteQueryKey(options),
    }
  );
};

export const getAdminOrdersQueryKey = (options?: Options<GetAdminOrdersData>) =>
  createQueryKey('getAdminOrders', options);

/**
 * Get all orders with filtering and sorting (admin only)
 * Retrieves a paginated list of all orders in the system with comprehensive filtering and sorting capabilities. This endpoint is restricted to admin users and provides full visibility into all orders regardless of customer or driver assignment. Supports filtering by status, price range, date range, customer/driver ID, and search across addresses and descriptions.
 */
export const getAdminOrdersOptions = (options?: Options<GetAdminOrdersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAdminOrders({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAdminOrdersQueryKey(options),
  });
};

export const getAdminOrdersInfiniteQueryKey = (
  options?: Options<GetAdminOrdersData>
): QueryKey<Options<GetAdminOrdersData>> => createQueryKey('getAdminOrders', options, true);

/**
 * Get all orders with filtering and sorting (admin only)
 * Retrieves a paginated list of all orders in the system with comprehensive filtering and sorting capabilities. This endpoint is restricted to admin users and provides full visibility into all orders regardless of customer or driver assignment. Supports filtering by status, price range, date range, customer/driver ID, and search across addresses and descriptions.
 */
export const getAdminOrdersInfiniteOptions = (options?: Options<GetAdminOrdersData>) => {
  return infiniteQueryOptions<
    GetAdminOrdersResponse,
    GetAdminOrdersError,
    InfiniteData<GetAdminOrdersResponse>,
    QueryKey<Options<GetAdminOrdersData>>,
    number | Pick<QueryKey<Options<GetAdminOrdersData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetAdminOrdersData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getAdminOrders({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getAdminOrdersInfiniteQueryKey(options),
    }
  );
};

export const getAdminDriverApplicationsQueryKey = (
  options?: Options<GetAdminDriverApplicationsData>
) => createQueryKey('getAdminDriverApplications', options);

/**
 * Get all driver applications with filtering and sorting (admin only)
 * Retrieves a paginated list of all driver applications in the system with comprehensive filtering and sorting capabilities. This endpoint is restricted to admin users and provides full visibility into all driver applications regardless of status. Supports filtering by application status, date range, order ID, driver ID, and search across application messages.
 */
export const getAdminDriverApplicationsOptions = (
  options?: Options<GetAdminDriverApplicationsData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAdminDriverApplications({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAdminDriverApplicationsQueryKey(options),
  });
};

export const getAdminDriverApplicationsInfiniteQueryKey = (
  options?: Options<GetAdminDriverApplicationsData>
): QueryKey<Options<GetAdminDriverApplicationsData>> =>
  createQueryKey('getAdminDriverApplications', options, true);

/**
 * Get all driver applications with filtering and sorting (admin only)
 * Retrieves a paginated list of all driver applications in the system with comprehensive filtering and sorting capabilities. This endpoint is restricted to admin users and provides full visibility into all driver applications regardless of status. Supports filtering by application status, date range, order ID, driver ID, and search across application messages.
 */
export const getAdminDriverApplicationsInfiniteOptions = (
  options?: Options<GetAdminDriverApplicationsData>
) => {
  return infiniteQueryOptions<
    GetAdminDriverApplicationsResponse,
    GetAdminDriverApplicationsError,
    InfiniteData<GetAdminDriverApplicationsResponse>,
    QueryKey<Options<GetAdminDriverApplicationsData>>,
    | number
    | Pick<
        QueryKey<Options<GetAdminDriverApplicationsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetAdminDriverApplicationsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getAdminDriverApplications({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getAdminDriverApplicationsInfiniteQueryKey(options),
    }
  );
};

/**
 * Update user role (admin only)
 * Updates the role of a specific user. This endpoint allows admins to promote users to admin status, change drivers to customers, or vice versa. This is a powerful administrative function that should be used carefully.
 */
export const patchAdminUsersByIdRoleMutation = (
  options?: Partial<Options<PatchAdminUsersByIdRoleData>>
): UseMutationOptions<
  PatchAdminUsersByIdRoleResponse,
  PatchAdminUsersByIdRoleError,
  Options<PatchAdminUsersByIdRoleData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchAdminUsersByIdRoleResponse,
    PatchAdminUsersByIdRoleError,
    Options<PatchAdminUsersByIdRoleData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchAdminUsersByIdRole({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postAdminCleanupQueryKey = (options?: Options<PostAdminCleanupData>) =>
  createQueryKey('postAdminCleanup', options);

/**
 * Cleanup expired blacklisted tokens (admin only)
 * Removes expired blacklisted tokens from the database to prevent accumulation. This is an administrative maintenance operation that should be performed periodically to keep the database clean.
 */
export const postAdminCleanupOptions = (options?: Options<PostAdminCleanupData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postAdminCleanup({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postAdminCleanupQueryKey(options),
  });
};

/**
 * Cleanup expired blacklisted tokens (admin only)
 * Removes expired blacklisted tokens from the database to prevent accumulation. This is an administrative maintenance operation that should be performed periodically to keep the database clean.
 */
export const postAdminCleanupMutation = (
  options?: Partial<Options<PostAdminCleanupData>>
): UseMutationOptions<
  PostAdminCleanupResponse,
  PostAdminCleanupError,
  Options<PostAdminCleanupData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAdminCleanupResponse,
    PostAdminCleanupError,
    Options<PostAdminCleanupData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postAdminCleanup({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postAuthLoginQueryKey = (options: Options<PostAuthLoginData>) =>
  createQueryKey('postAuthLogin', options);

/**
 * Authenticate user and obtain access and refresh tokens
 * Authenticates a user with email and password credentials, returning both a JWT access token and a refresh token. The access token is short-lived (15 minutes) and should be used for API requests. The refresh token is long-lived (30 days) and can be used to obtain new access tokens.
 */
export const postAuthLoginOptions = (options: Options<PostAuthLoginData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postAuthLogin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postAuthLoginQueryKey(options),
  });
};

/**
 * Authenticate user and obtain access and refresh tokens
 * Authenticates a user with email and password credentials, returning both a JWT access token and a refresh token. The access token is short-lived (15 minutes) and should be used for API requests. The refresh token is long-lived (30 days) and can be used to obtain new access tokens.
 */
export const postAuthLoginMutation = (
  options?: Partial<Options<PostAuthLoginData>>
): UseMutationOptions<PostAuthLoginResponse, PostAuthLoginError, Options<PostAuthLoginData>> => {
  const mutationOptions: UseMutationOptions<
    PostAuthLoginResponse,
    PostAuthLoginError,
    Options<PostAuthLoginData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postAuthLogin({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postAuthRegisterQueryKey = (options: Options<PostAuthRegisterData>) =>
  createQueryKey('postAuthRegister', options);

/**
 * Create a new user account
 * Creates a new user account in the cargo delivery system. Users can register as either drivers or customers. The account is immediately active upon creation, and both access and refresh tokens are provided for immediate access. Email addresses must be unique across the system.
 */
export const postAuthRegisterOptions = (options: Options<PostAuthRegisterData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postAuthRegister({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postAuthRegisterQueryKey(options),
  });
};

/**
 * Create a new user account
 * Creates a new user account in the cargo delivery system. Users can register as either drivers or customers. The account is immediately active upon creation, and both access and refresh tokens are provided for immediate access. Email addresses must be unique across the system.
 */
export const postAuthRegisterMutation = (
  options?: Partial<Options<PostAuthRegisterData>>
): UseMutationOptions<
  PostAuthRegisterResponse,
  PostAuthRegisterError,
  Options<PostAuthRegisterData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAuthRegisterResponse,
    PostAuthRegisterError,
    Options<PostAuthRegisterData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postAuthRegister({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postAuthRefreshQueryKey = (options: Options<PostAuthRefreshData>) =>
  createQueryKey('postAuthRefresh', options);

/**
 * Refresh access token
 * Exchanges a valid refresh token for a new access token. This endpoint should be used when the access token expires. The refresh token remains valid and can be reused until it expires or is revoked.
 */
export const postAuthRefreshOptions = (options: Options<PostAuthRefreshData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postAuthRefresh({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postAuthRefreshQueryKey(options),
  });
};

/**
 * Refresh access token
 * Exchanges a valid refresh token for a new access token. This endpoint should be used when the access token expires. The refresh token remains valid and can be reused until it expires or is revoked.
 */
export const postAuthRefreshMutation = (
  options?: Partial<Options<PostAuthRefreshData>>
): UseMutationOptions<
  PostAuthRefreshResponse,
  PostAuthRefreshError,
  Options<PostAuthRefreshData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAuthRefreshResponse,
    PostAuthRefreshError,
    Options<PostAuthRefreshData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postAuthRefresh({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postAuthLogoutQueryKey = (options: Options<PostAuthLogoutData>) =>
  createQueryKey('postAuthLogout', options);

/**
 * Logout and revoke refresh token
 * Logs out the user by revoking the provided refresh token. This prevents the refresh token from being used to generate new access tokens. The access token will remain valid until it expires naturally.
 */
export const postAuthLogoutOptions = (options: Options<PostAuthLogoutData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postAuthLogout({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postAuthLogoutQueryKey(options),
  });
};

/**
 * Logout and revoke refresh token
 * Logs out the user by revoking the provided refresh token. This prevents the refresh token from being used to generate new access tokens. The access token will remain valid until it expires naturally.
 */
export const postAuthLogoutMutation = (
  options?: Partial<Options<PostAuthLogoutData>>
): UseMutationOptions<PostAuthLogoutResponse, PostAuthLogoutError, Options<PostAuthLogoutData>> => {
  const mutationOptions: UseMutationOptions<
    PostAuthLogoutResponse,
    PostAuthLogoutError,
    Options<PostAuthLogoutData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postAuthLogout({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postAuthLogoutAllQueryKey = (options?: Options<PostAuthLogoutAllData>) =>
  createQueryKey('postAuthLogoutAll', options);

/**
 * Logout from all devices
 * Revokes all refresh tokens for the authenticated user, effectively logging them out from all devices. This requires a valid access token in the Authorization header. All existing refresh tokens will be invalidated.
 */
export const postAuthLogoutAllOptions = (options?: Options<PostAuthLogoutAllData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postAuthLogoutAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postAuthLogoutAllQueryKey(options),
  });
};

/**
 * Logout from all devices
 * Revokes all refresh tokens for the authenticated user, effectively logging them out from all devices. This requires a valid access token in the Authorization header. All existing refresh tokens will be invalidated.
 */
export const postAuthLogoutAllMutation = (
  options?: Partial<Options<PostAuthLogoutAllData>>
): UseMutationOptions<
  PostAuthLogoutAllResponse,
  PostAuthLogoutAllError,
  Options<PostAuthLogoutAllData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAuthLogoutAllResponse,
    PostAuthLogoutAllError,
    Options<PostAuthLogoutAllData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postAuthLogoutAll({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAuthMeQueryKey = (options?: Options<GetAuthMeData>) =>
  createQueryKey('getAuthMe', options);

/**
 * Get current authenticated user information
 * Retrieves the profile information of the currently authenticated user based on the provided JWT token. This endpoint is useful for displaying user profile data, verifying authentication status, and determining user permissions based on their role. No additional parameters are required as the user is identified from the token.
 */
export const getAuthMeOptions = (options?: Options<GetAuthMeData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAuthMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAuthMeQueryKey(options),
  });
};

export const getUsersQueryKey = (options?: Options<GetUsersData>) =>
  createQueryKey('getUsers', options);

/**
 * Get all users in the system with filtering and sorting
 * Retrieves a paginated list of all registered users in the cargo delivery system with comprehensive filtering and sorting capabilities. This endpoint provides access to user profiles for administrative purposes, driver discovery, and system management. Supports filtering by role, location, subscription status, and search across names and emails. Results can be sorted by various fields including name, role, and registration date.
 */
export const getUsersOptions = (options?: Options<GetUsersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUsersQueryKey(options),
  });
};

export const getUsersInfiniteQueryKey = (
  options?: Options<GetUsersData>
): QueryKey<Options<GetUsersData>> => createQueryKey('getUsers', options, true);

/**
 * Get all users in the system with filtering and sorting
 * Retrieves a paginated list of all registered users in the cargo delivery system with comprehensive filtering and sorting capabilities. This endpoint provides access to user profiles for administrative purposes, driver discovery, and system management. Supports filtering by role, location, subscription status, and search across names and emails. Results can be sorted by various fields including name, role, and registration date.
 */
export const getUsersInfiniteOptions = (options?: Options<GetUsersData>) => {
  return infiniteQueryOptions<
    GetUsersResponse,
    GetUsersError,
    InfiniteData<GetUsersResponse>,
    QueryKey<Options<GetUsersData>>,
    number | Pick<QueryKey<Options<GetUsersData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetUsersData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getUsersInfiniteQueryKey(options),
    }
  );
};

export const postUsersQueryKey = (options: Options<PostUsersData>) =>
  createQueryKey('postUsers', options);

/**
 * Create a new user account
 * Creates a new user account in the cargo delivery system. This endpoint allows for programmatic user registration and is typically used for administrative user creation or bulk user imports. The user will be created with the specified role (driver or customer) and can immediately begin using the system.
 */
export const postUsersOptions = (options: Options<PostUsersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postUsersQueryKey(options),
  });
};

/**
 * Create a new user account
 * Creates a new user account in the cargo delivery system. This endpoint allows for programmatic user registration and is typically used for administrative user creation or bulk user imports. The user will be created with the specified role (driver or customer) and can immediately begin using the system.
 */
export const postUsersMutation = (
  options?: Partial<Options<PostUsersData>>
): UseMutationOptions<PostUsersResponse, PostUsersError, Options<PostUsersData>> => {
  const mutationOptions: UseMutationOptions<
    PostUsersResponse,
    PostUsersError,
    Options<PostUsersData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postUsers({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a user account
 * Permanently removes a user account from the cargo delivery system. This action is irreversible and will delete all associated user data. Before deletion, ensure that the user has no active orders or pending applications. This endpoint is typically used for account deactivation or administrative cleanup.
 */
export const deleteUsersByIdMutation = (
  options?: Partial<Options<DeleteUsersByIdData>>
): UseMutationOptions<
  DeleteUsersByIdResponse,
  DeleteUsersByIdError,
  Options<DeleteUsersByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteUsersByIdResponse,
    DeleteUsersByIdError,
    Options<DeleteUsersByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteUsersById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getUsersByIdQueryKey = (options: Options<GetUsersByIdData>) =>
  createQueryKey('getUsersById', options);

/**
 * Get a specific user by ID
 * Retrieves detailed information about a specific user in the cargo delivery system. This endpoint is useful for viewing user profiles, verifying driver credentials, or displaying customer information during order management. Only public profile information is returned for security.
 */
export const getUsersByIdOptions = (options: Options<GetUsersByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUsersById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUsersByIdQueryKey(options),
  });
};

/**
 * Update user profile information
 * Updates specific fields of a user's profile information. This endpoint allows for partial updates of user data such as name, email, phone number, or avatar. Only the fields provided in the request body will be updated, leaving other fields unchanged. This is commonly used for profile management and administrative updates.
 */
export const patchUsersByIdMutation = (
  options?: Partial<Options<PatchUsersByIdData>>
): UseMutationOptions<PatchUsersByIdResponse, PatchUsersByIdError, Options<PatchUsersByIdData>> => {
  const mutationOptions: UseMutationOptions<
    PatchUsersByIdResponse,
    PatchUsersByIdError,
    Options<PatchUsersByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchUsersById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getOrdersQueryKey = (options?: Options<GetOrdersData>) =>
  createQueryKey('getOrders', options);

/**
 * Get orders based on user role with filtering and sorting
 * Retrieves paginated orders filtered by the authenticated user's role and permissions. Customers see only their own orders, drivers see all pending orders (with customer details only for orders assigned to them), and admins see all orders in the system. Supports comprehensive filtering by status, price range, date range, customer/driver ID, and search across addresses and descriptions. Results can be sorted by various fields including price, status, and dates.
 */
export const getOrdersOptions = (options?: Options<GetOrdersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOrders({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getOrdersQueryKey(options),
  });
};

export const getOrdersInfiniteQueryKey = (
  options?: Options<GetOrdersData>
): QueryKey<Options<GetOrdersData>> => createQueryKey('getOrders', options, true);

/**
 * Get orders based on user role with filtering and sorting
 * Retrieves paginated orders filtered by the authenticated user's role and permissions. Customers see only their own orders, drivers see all pending orders (with customer details only for orders assigned to them), and admins see all orders in the system. Supports comprehensive filtering by status, price range, date range, customer/driver ID, and search across addresses and descriptions. Results can be sorted by various fields including price, status, and dates.
 */
export const getOrdersInfiniteOptions = (options?: Options<GetOrdersData>) => {
  return infiniteQueryOptions<
    GetOrdersResponse,
    GetOrdersError,
    InfiniteData<GetOrdersResponse>,
    QueryKey<Options<GetOrdersData>>,
    number | Pick<QueryKey<Options<GetOrdersData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetOrdersData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getOrders({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getOrdersInfiniteQueryKey(options),
    }
  );
};

export const postOrdersQueryKey = (options: Options<PostOrdersData>) =>
  createQueryKey('postOrders', options);

/**
 * Create a new delivery order
 * Creates a new delivery order in the system. This endpoint is restricted to customers who can create orders for package delivery. The order will be created with 'pending' status and made available for driver applications. All delivery details, pricing, and timing information must be provided.
 */
export const postOrdersOptions = (options: Options<PostOrdersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postOrders({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postOrdersQueryKey(options),
  });
};

/**
 * Create a new delivery order
 * Creates a new delivery order in the system. This endpoint is restricted to customers who can create orders for package delivery. The order will be created with 'pending' status and made available for driver applications. All delivery details, pricing, and timing information must be provided.
 */
export const postOrdersMutation = (
  options?: Partial<Options<PostOrdersData>>
): UseMutationOptions<PostOrdersResponse, PostOrdersError, Options<PostOrdersData>> => {
  const mutationOptions: UseMutationOptions<
    PostOrdersResponse,
    PostOrdersError,
    Options<PostOrdersData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postOrders({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getOrdersAvailableQueryKey = (options?: Options<GetOrdersAvailableData>) =>
  createQueryKey('getOrdersAvailable', options);

/**
 * Get all available orders for driver applications
 * Retrieves paginated delivery orders that are currently available for driver applications. These are orders that have been created by customers but don't have an assigned driver yet. This endpoint serves as the marketplace where drivers can browse and choose which orders to apply for based on location, price, and package details. Customer information is intentionally excluded for privacy reasons.
 */
export const getOrdersAvailableOptions = (options?: Options<GetOrdersAvailableData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOrdersAvailable({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getOrdersAvailableQueryKey(options),
  });
};

export const getOrdersAvailableInfiniteQueryKey = (
  options?: Options<GetOrdersAvailableData>
): QueryKey<Options<GetOrdersAvailableData>> => createQueryKey('getOrdersAvailable', options, true);

/**
 * Get all available orders for driver applications
 * Retrieves paginated delivery orders that are currently available for driver applications. These are orders that have been created by customers but don't have an assigned driver yet. This endpoint serves as the marketplace where drivers can browse and choose which orders to apply for based on location, price, and package details. Customer information is intentionally excluded for privacy reasons.
 */
export const getOrdersAvailableInfiniteOptions = (options?: Options<GetOrdersAvailableData>) => {
  return infiniteQueryOptions<
    GetOrdersAvailableResponse,
    GetOrdersAvailableError,
    InfiniteData<GetOrdersAvailableResponse>,
    QueryKey<Options<GetOrdersAvailableData>>,
    | number
    | Pick<QueryKey<Options<GetOrdersAvailableData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetOrdersAvailableData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getOrdersAvailable({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getOrdersAvailableInfiniteQueryKey(options),
    }
  );
};

/**
 * Cancel/delete a delivery order
 * Cancels or permanently removes a delivery order from the system. This action is restricted to customers who own the order and admin users. Orders with assigned drivers or in progress cannot be deleted and must be cancelled through status updates instead. This action is irreversible.
 */
export const deleteOrdersByIdMutation = (
  options?: Partial<Options<DeleteOrdersByIdData>>
): UseMutationOptions<
  DeleteOrdersByIdResponse,
  DeleteOrdersByIdError,
  Options<DeleteOrdersByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteOrdersByIdResponse,
    DeleteOrdersByIdError,
    Options<DeleteOrdersByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteOrdersById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getOrdersByIdQueryKey = (options: Options<GetOrdersByIdData>) =>
  createQueryKey('getOrdersById', options);

/**
 * Get a specific order by ID
 * Retrieves detailed information about a specific delivery order. Access is restricted based on user role: customers can only view their own orders, drivers can view pending orders (with customer details only for assigned orders), and admins can view any order. This endpoint provides complete order tracking information while protecting customer privacy for unassigned orders.
 */
export const getOrdersByIdOptions = (options: Options<GetOrdersByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOrdersById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getOrdersByIdQueryKey(options),
  });
};

/**
 * Update order information
 * Updates specific fields of an existing delivery order. Access is controlled by user role and order ownership. Customers can update their orders before driver assignment, drivers can update delivery status and tracking information, and admins can update any order. Only provided fields will be updated, allowing for flexible partial updates.
 */
export const patchOrdersByIdMutation = (
  options?: Partial<Options<PatchOrdersByIdData>>
): UseMutationOptions<
  PatchOrdersByIdResponse,
  PatchOrdersByIdError,
  Options<PatchOrdersByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchOrdersByIdResponse,
    PatchOrdersByIdError,
    Options<PatchOrdersByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchOrdersById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getOrdersByIdApplicationsQueryKey = (
  options: Options<GetOrdersByIdApplicationsData>
) => createQueryKey('getOrdersByIdApplications', options);

/**
 * Get all driver applications for a specific order with filtering
 * Retrieves paginated driver applications submitted for a specific delivery order with comprehensive filtering and sorting capabilities. This endpoint is typically used by order owners (customers) to view which drivers have applied to fulfill their delivery request and make informed decisions about driver selection. Supports filtering by application status, date range, and search across driver information.
 */
export const getOrdersByIdApplicationsOptions = (
  options: Options<GetOrdersByIdApplicationsData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOrdersByIdApplications({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getOrdersByIdApplicationsQueryKey(options),
  });
};

export const getOrdersByIdApplicationsInfiniteQueryKey = (
  options: Options<GetOrdersByIdApplicationsData>
): QueryKey<Options<GetOrdersByIdApplicationsData>> =>
  createQueryKey('getOrdersByIdApplications', options, true);

/**
 * Get all driver applications for a specific order with filtering
 * Retrieves paginated driver applications submitted for a specific delivery order with comprehensive filtering and sorting capabilities. This endpoint is typically used by order owners (customers) to view which drivers have applied to fulfill their delivery request and make informed decisions about driver selection. Supports filtering by application status, date range, and search across driver information.
 */
export const getOrdersByIdApplicationsInfiniteOptions = (
  options: Options<GetOrdersByIdApplicationsData>
) => {
  return infiniteQueryOptions<
    GetOrdersByIdApplicationsResponse,
    GetOrdersByIdApplicationsError,
    InfiniteData<GetOrdersByIdApplicationsResponse>,
    QueryKey<Options<GetOrdersByIdApplicationsData>>,
    | number
    | Pick<
        QueryKey<Options<GetOrdersByIdApplicationsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetOrdersByIdApplicationsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getOrdersByIdApplications({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getOrdersByIdApplicationsInfiniteQueryKey(options),
    }
  );
};

export const getDriversByIdApplicationsQueryKey = (
  options: Options<GetDriversByIdApplicationsData>
) => createQueryKey('getDriversByIdApplications', options);

/**
 * Get all applications submitted by a specific driver with filtering
 * Retrieves the paginated application history for a specific driver with comprehensive filtering and sorting capabilities, including the status of each application and details about the orders they applied for. This endpoint helps drivers track their application activity and order statuses. Supports filtering by application status, date range, and search across order information.
 */
export const getDriversByIdApplicationsOptions = (
  options: Options<GetDriversByIdApplicationsData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDriversByIdApplications({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDriversByIdApplicationsQueryKey(options),
  });
};

export const getDriversByIdApplicationsInfiniteQueryKey = (
  options: Options<GetDriversByIdApplicationsData>
): QueryKey<Options<GetDriversByIdApplicationsData>> =>
  createQueryKey('getDriversByIdApplications', options, true);

/**
 * Get all applications submitted by a specific driver with filtering
 * Retrieves the paginated application history for a specific driver with comprehensive filtering and sorting capabilities, including the status of each application and details about the orders they applied for. This endpoint helps drivers track their application activity and order statuses. Supports filtering by application status, date range, and search across order information.
 */
export const getDriversByIdApplicationsInfiniteOptions = (
  options: Options<GetDriversByIdApplicationsData>
) => {
  return infiniteQueryOptions<
    GetDriversByIdApplicationsResponse,
    GetDriversByIdApplicationsError,
    InfiniteData<GetDriversByIdApplicationsResponse>,
    QueryKey<Options<GetDriversByIdApplicationsData>>,
    | number
    | Pick<
        QueryKey<Options<GetDriversByIdApplicationsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetDriversByIdApplicationsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getDriversByIdApplications({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getDriversByIdApplicationsInfiniteQueryKey(options),
    }
  );
};

export const postDriverApplicationsQueryKey = (options: Options<PostDriverApplicationsData>) =>
  createQueryKey('postDriverApplications', options);

/**
 * Submit a new driver application for an order
 * Allows a driver to apply for a specific delivery order. The system will validate that the order is still available and that the driver hasn't already applied for this order. Once submitted, the application will be available for review by the order owner.
 */
export const postDriverApplicationsOptions = (options: Options<PostDriverApplicationsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postDriverApplications({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postDriverApplicationsQueryKey(options),
  });
};

/**
 * Submit a new driver application for an order
 * Allows a driver to apply for a specific delivery order. The system will validate that the order is still available and that the driver hasn't already applied for this order. Once submitted, the application will be available for review by the order owner.
 */
export const postDriverApplicationsMutation = (
  options?: Partial<Options<PostDriverApplicationsData>>
): UseMutationOptions<
  PostDriverApplicationsResponse,
  PostDriverApplicationsError,
  Options<PostDriverApplicationsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostDriverApplicationsResponse,
    PostDriverApplicationsError,
    Options<PostDriverApplicationsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postDriverApplications({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update the status of a driver application
 * Allows order owners to accept or reject driver applications for their orders. When an application is accepted, the driver is assigned to the order and other pending applications for the same order are automatically rejected. This endpoint is crucial for the order assignment workflow.
 */
export const patchDriverApplicationsByIdMutation = (
  options?: Partial<Options<PatchDriverApplicationsByIdData>>
): UseMutationOptions<
  PatchDriverApplicationsByIdResponse,
  PatchDriverApplicationsByIdError,
  Options<PatchDriverApplicationsByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchDriverApplicationsByIdResponse,
    PatchDriverApplicationsByIdError,
    Options<PatchDriverApplicationsByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchDriverApplicationsById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getRealtimeWebsocketQueryKey = (options?: Options<GetRealtimeWebsocketData>) =>
  createQueryKey('getRealtimeWebsocket', options);

/**
 * Establish WebSocket connection for real-time updates
 * Establishes a WebSocket connection for real-time updates. Requires authentication via JWT token in Authorization header. Users will receive real-time events based on their role and access permissions.
 */
export const getRealtimeWebsocketOptions = (options?: Options<GetRealtimeWebsocketData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRealtimeWebsocket({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRealtimeWebsocketQueryKey(options),
  });
};

export const postRealtimeBroadcastQueryKey = (options?: Options<PostRealtimeBroadcastData>) =>
  createQueryKey('postRealtimeBroadcast', options);

/**
 * Broadcast real-time event to connected clients
 * Broadcasts a real-time event to connected WebSocket clients. Requires authentication and appropriate permissions. Events are delivered based on targeting rules and user access permissions.
 */
export const postRealtimeBroadcastOptions = (options?: Options<PostRealtimeBroadcastData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postRealtimeBroadcast({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postRealtimeBroadcastQueryKey(options),
  });
};

/**
 * Broadcast real-time event to connected clients
 * Broadcasts a real-time event to connected WebSocket clients. Requires authentication and appropriate permissions. Events are delivered based on targeting rules and user access permissions.
 */
export const postRealtimeBroadcastMutation = (
  options?: Partial<Options<PostRealtimeBroadcastData>>
): UseMutationOptions<
  PostRealtimeBroadcastResponse,
  PostRealtimeBroadcastError,
  Options<PostRealtimeBroadcastData>
> => {
  const mutationOptions: UseMutationOptions<
    PostRealtimeBroadcastResponse,
    PostRealtimeBroadcastError,
    Options<PostRealtimeBroadcastData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postRealtimeBroadcast({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getRealtimeConnectionsQueryKey = (options?: Options<GetRealtimeConnectionsData>) =>
  createQueryKey('getRealtimeConnections', options);

/**
 * Get active real-time connections
 * Retrieves information about active real-time WebSocket connections. Access is restricted based on user role - admins can see all connections, others can only see their own.
 */
export const getRealtimeConnectionsOptions = (options?: Options<GetRealtimeConnectionsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRealtimeConnections({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRealtimeConnectionsQueryKey(options),
  });
};

export const getRealtimeHealthQueryKey = (options?: Options<GetRealtimeHealthData>) =>
  createQueryKey('getRealtimeHealth', options);

/**
 * Check real-time service health
 * Health check endpoint for the real-time service. Public endpoint that doesn't require authentication.
 */
export const getRealtimeHealthOptions = (options?: Options<GetRealtimeHealthData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRealtimeHealth({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRealtimeHealthQueryKey(options),
  });
};
