// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type {
  GetData,
  GetResponses,
  GetAdminDashboardStatsData,
  GetAdminDashboardStatsResponses,
  GetAdminDashboardStatsErrors,
  GetAdminUsersData,
  GetAdminUsersResponses,
  GetAdminUsersErrors,
  GetAdminOrdersData,
  GetAdminOrdersResponses,
  GetAdminOrdersErrors,
  GetAdminDriverApplicationsData,
  GetAdminDriverApplicationsResponses,
  GetAdminDriverApplicationsErrors,
  PatchAdminUsersByIdRoleData,
  PatchAdminUsersByIdRoleResponses,
  PatchAdminUsersByIdRoleErrors,
  PostAdminCleanupData,
  PostAdminCleanupResponses,
  PostAdminCleanupErrors,
  PostAuthLoginData,
  PostAuthLoginResponses,
  PostAuthLoginErrors,
  PostAuthRegisterData,
  PostAuthRegisterResponses,
  PostAuthRegisterErrors,
  PostAuthRefreshData,
  PostAuthRefreshResponses,
  PostAuthRefreshErrors,
  PostAuthLogoutData,
  PostAuthLogoutResponses,
  PostAuthLogoutErrors,
  PostAuthLogoutAllData,
  PostAuthLogoutAllResponses,
  PostAuthLogoutAllErrors,
  GetAuthMeData,
  GetAuthMeResponses,
  GetAuthMeErrors,
  GetUsersData,
  GetUsersResponses,
  GetUsersErrors,
  PostUsersData,
  PostUsersResponses,
  PostUsersErrors,
  DeleteUsersByIdData,
  DeleteUsersByIdResponses,
  DeleteUsersByIdErrors,
  GetUsersByIdData,
  GetUsersByIdResponses,
  GetUsersByIdErrors,
  PatchUsersByIdData,
  PatchUsersByIdResponses,
  PatchUsersByIdErrors,
  GetOrdersData,
  GetOrdersResponses,
  GetOrdersErrors,
  PostOrdersData,
  PostOrdersResponses,
  PostOrdersErrors,
  GetOrdersAvailableData,
  GetOrdersAvailableResponses,
  GetOrdersAvailableErrors,
  DeleteOrdersByIdData,
  DeleteOrdersByIdResponses,
  DeleteOrdersByIdErrors,
  GetOrdersByIdData,
  GetOrdersByIdResponses,
  GetOrdersByIdErrors,
  PatchOrdersByIdData,
  PatchOrdersByIdResponses,
  PatchOrdersByIdErrors,
  GetOrdersByIdApplicationsData,
  GetOrdersByIdApplicationsResponses,
  GetOrdersByIdApplicationsErrors,
  GetDriversByIdApplicationsData,
  GetDriversByIdApplicationsResponses,
  GetDriversByIdApplicationsErrors,
  PostDriverApplicationsData,
  PostDriverApplicationsResponses,
  PostDriverApplicationsErrors,
  PatchDriverApplicationsByIdData,
  PatchDriverApplicationsByIdResponses,
  PatchDriverApplicationsByIdErrors,
  GetRealtimeWebsocketData,
  GetRealtimeWebsocketErrors,
  PostRealtimeBroadcastData,
  PostRealtimeBroadcastResponses,
  PostRealtimeBroadcastErrors,
  GetRealtimeConnectionsData,
  GetRealtimeConnectionsResponses,
  GetRealtimeConnectionsErrors,
  GetRealtimeHealthData,
  GetRealtimeHealthResponses,
  GetRealtimeHealthErrors,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * API health check and information
 * Returns comprehensive information about the Cargo API service including health status, environment details, and service availability. This endpoint serves as a global health check for monitoring systems worldwide and provides confirmation that the API is running and accessible.
 */
export const get = <ThrowOnError extends boolean = false>(
  options?: Options<GetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<GetResponses, unknown, ThrowOnError>({
    url: '/',
    ...options,
  });
};

/**
 * Get admin dashboard statistics
 * Retrieves comprehensive statistics for the admin dashboard including user counts, order statistics, and application metrics. This endpoint provides a high-level overview of the system's current state.
 */
export const getAdminDashboardStats = <ThrowOnError extends boolean = false>(
  options?: Options<GetAdminDashboardStatsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetAdminDashboardStatsResponses,
    GetAdminDashboardStatsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/admin/dashboard/stats',
    ...options,
  });
};

/**
 * Get all users with filtering and sorting (admin only)
 * Retrieves a paginated list of all users in the system with comprehensive filtering and sorting capabilities. This endpoint is restricted to admin users and provides detailed user information including creation dates and subscription status. Supports filtering by role, location, subscription status, and search across user information.
 */
export const getAdminUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetAdminUsersData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetAdminUsersResponses,
    GetAdminUsersErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/admin/users',
    ...options,
  });
};

/**
 * Get all orders with filtering and sorting (admin only)
 * Retrieves a paginated list of all orders in the system with comprehensive filtering and sorting capabilities. This endpoint is restricted to admin users and provides full visibility into all orders regardless of customer or driver assignment. Supports filtering by status, price range, date range, customer/driver ID, and search across addresses and descriptions.
 */
export const getAdminOrders = <ThrowOnError extends boolean = false>(
  options?: Options<GetAdminOrdersData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetAdminOrdersResponses,
    GetAdminOrdersErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/admin/orders',
    ...options,
  });
};

/**
 * Get all driver applications with filtering and sorting (admin only)
 * Retrieves a paginated list of all driver applications in the system with comprehensive filtering and sorting capabilities. This endpoint is restricted to admin users and provides full visibility into all driver applications regardless of status. Supports filtering by application status, date range, order ID, driver ID, and search across application messages.
 */
export const getAdminDriverApplications = <ThrowOnError extends boolean = false>(
  options?: Options<GetAdminDriverApplicationsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetAdminDriverApplicationsResponses,
    GetAdminDriverApplicationsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/admin/driver-applications',
    ...options,
  });
};

/**
 * Update user role (admin only)
 * Updates the role of a specific user. This endpoint allows admins to promote users to admin status, change drivers to customers, or vice versa. This is a powerful administrative function that should be used carefully.
 */
export const patchAdminUsersByIdRole = <ThrowOnError extends boolean = false>(
  options: Options<PatchAdminUsersByIdRoleData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchAdminUsersByIdRoleResponses,
    PatchAdminUsersByIdRoleErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/admin/users/{id}/role',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Cleanup expired blacklisted tokens (admin only)
 * Removes expired blacklisted tokens from the database to prevent accumulation. This is an administrative maintenance operation that should be performed periodically to keep the database clean.
 */
export const postAdminCleanup = <ThrowOnError extends boolean = false>(
  options?: Options<PostAdminCleanupData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    PostAdminCleanupResponses,
    PostAdminCleanupErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/admin/cleanup',
    ...options,
  });
};

/**
 * Authenticate user and obtain access and refresh tokens
 * Authenticates a user with email and password credentials, returning both a JWT access token and a refresh token. The access token is short-lived (15 minutes) and should be used for API requests. The refresh token is long-lived (30 days) and can be used to obtain new access tokens.
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(
  options: Options<PostAuthLoginData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostAuthLoginResponses,
    PostAuthLoginErrors,
    ThrowOnError
  >({
    url: '/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Create a new user account
 * Creates a new user account in the cargo delivery system. Users can register as either drivers or customers. The account is immediately active upon creation, and both access and refresh tokens are provided for immediate access. Email addresses must be unique across the system.
 */
export const postAuthRegister = <ThrowOnError extends boolean = false>(
  options: Options<PostAuthRegisterData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostAuthRegisterResponses,
    PostAuthRegisterErrors,
    ThrowOnError
  >({
    url: '/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Refresh access token
 * Exchanges a valid refresh token for a new access token. This endpoint should be used when the access token expires. The refresh token remains valid and can be reused until it expires or is revoked.
 */
export const postAuthRefresh = <ThrowOnError extends boolean = false>(
  options: Options<PostAuthRefreshData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostAuthRefreshResponses,
    PostAuthRefreshErrors,
    ThrowOnError
  >({
    url: '/auth/refresh',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Logout and revoke refresh token
 * Logs out the user by revoking the provided refresh token. This prevents the refresh token from being used to generate new access tokens. The access token will remain valid until it expires naturally.
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(
  options: Options<PostAuthLogoutData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostAuthLogoutResponses,
    PostAuthLogoutErrors,
    ThrowOnError
  >({
    url: '/auth/logout',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Logout from all devices
 * Revokes all refresh tokens for the authenticated user, effectively logging them out from all devices. This requires a valid access token in the Authorization header. All existing refresh tokens will be invalidated.
 */
export const postAuthLogoutAll = <ThrowOnError extends boolean = false>(
  options?: Options<PostAuthLogoutAllData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    PostAuthLogoutAllResponses,
    PostAuthLogoutAllErrors,
    ThrowOnError
  >({
    url: '/auth/logout-all',
    ...options,
  });
};

/**
 * Get current authenticated user information
 * Retrieves the profile information of the currently authenticated user based on the provided JWT token. This endpoint is useful for displaying user profile data, verifying authentication status, and determining user permissions based on their role. No additional parameters are required as the user is identified from the token.
 */
export const getAuthMe = <ThrowOnError extends boolean = false>(
  options?: Options<GetAuthMeData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<GetAuthMeResponses, GetAuthMeErrors, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/auth/me',
    ...options,
  });
};

/**
 * Get all users in the system with filtering and sorting
 * Retrieves a paginated list of all registered users in the cargo delivery system with comprehensive filtering and sorting capabilities. This endpoint provides access to user profiles for administrative purposes, driver discovery, and system management. Supports filtering by role, location, subscription status, and search across names and emails. Results can be sorted by various fields including name, role, and registration date.
 */
export const getUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetUsersData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<GetUsersResponses, GetUsersErrors, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/users',
    ...options,
  });
};

/**
 * Create a new user account
 * Creates a new user account in the cargo delivery system. This endpoint allows for programmatic user registration and is typically used for administrative user creation or bulk user imports. The user will be created with the specified role (driver or customer) and can immediately begin using the system.
 */
export const postUsers = <ThrowOnError extends boolean = false>(
  options: Options<PostUsersData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<PostUsersResponses, PostUsersErrors, ThrowOnError>({
    url: '/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete a user account
 * Permanently removes a user account from the cargo delivery system. This action is irreversible and will delete all associated user data. Before deletion, ensure that the user has no active orders or pending applications. This endpoint is typically used for account deactivation or administrative cleanup.
 */
export const deleteUsersById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUsersByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteUsersByIdResponses,
    DeleteUsersByIdErrors,
    ThrowOnError
  >({
    url: '/users/{id}',
    ...options,
  });
};

/**
 * Get a specific user by ID
 * Retrieves detailed information about a specific user in the cargo delivery system. This endpoint is useful for viewing user profiles, verifying driver credentials, or displaying customer information during order management. Only public profile information is returned for security.
 */
export const getUsersById = <ThrowOnError extends boolean = false>(
  options: Options<GetUsersByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetUsersByIdResponses,
    GetUsersByIdErrors,
    ThrowOnError
  >({
    url: '/users/{id}',
    ...options,
  });
};

/**
 * Update user profile information
 * Updates specific fields of a user's profile information. This endpoint allows for partial updates of user data such as name, email, phone number, or avatar. Only the fields provided in the request body will be updated, leaving other fields unchanged. This is commonly used for profile management and administrative updates.
 */
export const patchUsersById = <ThrowOnError extends boolean = false>(
  options: Options<PatchUsersByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchUsersByIdResponses,
    PatchUsersByIdErrors,
    ThrowOnError
  >({
    url: '/users/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get orders based on user role with filtering and sorting
 * Retrieves paginated orders filtered by the authenticated user's role and permissions. Customers see only their own orders, drivers see all pending orders (with customer details only for orders assigned to them), and admins see all orders in the system. Supports comprehensive filtering by status, price range, date range, customer/driver ID, and search across addresses and descriptions. Results can be sorted by various fields including price, status, and dates.
 */
export const getOrders = <ThrowOnError extends boolean = false>(
  options?: Options<GetOrdersData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<GetOrdersResponses, GetOrdersErrors, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/orders',
    ...options,
  });
};

/**
 * Create a new delivery order
 * Creates a new delivery order in the system. This endpoint is restricted to customers who can create orders for package delivery. The order will be created with 'pending' status and made available for driver applications. All delivery details, pricing, and timing information must be provided.
 */
export const postOrders = <ThrowOnError extends boolean = false>(
  options: Options<PostOrdersData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostOrdersResponses,
    PostOrdersErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/orders',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get all available orders for driver applications
 * Retrieves paginated delivery orders that are currently available for driver applications. These are orders that have been created by customers but don't have an assigned driver yet. This endpoint serves as the marketplace where drivers can browse and choose which orders to apply for based on location, price, and package details. Customer information is intentionally excluded for privacy reasons.
 */
export const getOrdersAvailable = <ThrowOnError extends boolean = false>(
  options?: Options<GetOrdersAvailableData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetOrdersAvailableResponses,
    GetOrdersAvailableErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/orders/available',
    ...options,
  });
};

/**
 * Cancel/delete a delivery order
 * Cancels or permanently removes a delivery order from the system. This action is restricted to customers who own the order and admin users. Orders with assigned drivers or in progress cannot be deleted and must be cancelled through status updates instead. This action is irreversible.
 */
export const deleteOrdersById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteOrdersByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteOrdersByIdResponses,
    DeleteOrdersByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/orders/{id}',
    ...options,
  });
};

/**
 * Get a specific order by ID
 * Retrieves detailed information about a specific delivery order. Access is restricted based on user role: customers can only view their own orders, drivers can view pending orders (with customer details only for assigned orders), and admins can view any order. This endpoint provides complete order tracking information while protecting customer privacy for unassigned orders.
 */
export const getOrdersById = <ThrowOnError extends boolean = false>(
  options: Options<GetOrdersByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetOrdersByIdResponses,
    GetOrdersByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/orders/{id}',
    ...options,
  });
};

/**
 * Update order information
 * Updates specific fields of an existing delivery order. Access is controlled by user role and order ownership. Customers can update their orders before driver assignment, drivers can update delivery status and tracking information, and admins can update any order. Only provided fields will be updated, allowing for flexible partial updates.
 */
export const patchOrdersById = <ThrowOnError extends boolean = false>(
  options: Options<PatchOrdersByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchOrdersByIdResponses,
    PatchOrdersByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/orders/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get all driver applications for a specific order with filtering
 * Retrieves paginated driver applications submitted for a specific delivery order with comprehensive filtering and sorting capabilities. This endpoint is typically used by order owners (customers) to view which drivers have applied to fulfill their delivery request and make informed decisions about driver selection. Supports filtering by application status, date range, and search across driver information.
 */
export const getOrdersByIdApplications = <ThrowOnError extends boolean = false>(
  options: Options<GetOrdersByIdApplicationsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetOrdersByIdApplicationsResponses,
    GetOrdersByIdApplicationsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/orders/{id}/applications',
    ...options,
  });
};

/**
 * Get all applications submitted by a specific driver with filtering
 * Retrieves the paginated application history for a specific driver with comprehensive filtering and sorting capabilities, including the status of each application and details about the orders they applied for. This endpoint helps drivers track their application activity and order statuses. Supports filtering by application status, date range, and search across order information.
 */
export const getDriversByIdApplications = <ThrowOnError extends boolean = false>(
  options: Options<GetDriversByIdApplicationsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetDriversByIdApplicationsResponses,
    GetDriversByIdApplicationsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/drivers/{id}/applications',
    ...options,
  });
};

/**
 * Submit a new driver application for an order
 * Allows a driver to apply for a specific delivery order. The system will validate that the order is still available and that the driver hasn't already applied for this order. Once submitted, the application will be available for review by the order owner.
 */
export const postDriverApplications = <ThrowOnError extends boolean = false>(
  options: Options<PostDriverApplicationsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PostDriverApplicationsResponses,
    PostDriverApplicationsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/driver-applications',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Update the status of a driver application
 * Allows order owners to accept or reject driver applications for their orders. When an application is accepted, the driver is assigned to the order and other pending applications for the same order are automatically rejected. This endpoint is crucial for the order assignment workflow.
 */
export const patchDriverApplicationsById = <ThrowOnError extends boolean = false>(
  options: Options<PatchDriverApplicationsByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchDriverApplicationsByIdResponses,
    PatchDriverApplicationsByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/driver-applications/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Establish WebSocket connection for real-time updates
 * Establishes a WebSocket connection for real-time updates. Requires authentication via JWT token in Authorization header. Users will receive real-time events based on their role and access permissions.
 */
export const getRealtimeWebsocket = <ThrowOnError extends boolean = false>(
  options?: Options<GetRealtimeWebsocketData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<unknown, GetRealtimeWebsocketErrors, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/realtime/websocket',
    ...options,
  });
};

/**
 * Broadcast real-time event to connected clients
 * Broadcasts a real-time event to connected WebSocket clients. Requires authentication and appropriate permissions. Events are delivered based on targeting rules and user access permissions.
 */
export const postRealtimeBroadcast = <ThrowOnError extends boolean = false>(
  options?: Options<PostRealtimeBroadcastData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    PostRealtimeBroadcastResponses,
    PostRealtimeBroadcastErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/realtime/broadcast',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get active real-time connections
 * Retrieves information about active real-time WebSocket connections. Access is restricted based on user role - admins can see all connections, others can only see their own.
 */
export const getRealtimeConnections = <ThrowOnError extends boolean = false>(
  options?: Options<GetRealtimeConnectionsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetRealtimeConnectionsResponses,
    GetRealtimeConnectionsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/realtime/connections',
    ...options,
  });
};

/**
 * Check real-time service health
 * Health check endpoint for the real-time service. Public endpoint that doesn't require authentication.
 */
export const getRealtimeHealth = <ThrowOnError extends boolean = false>(
  options?: Options<GetRealtimeHealthData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetRealtimeHealthResponses,
    GetRealtimeHealthErrors,
    ThrowOnError
  >({
    url: '/realtime/health',
    ...options,
  });
};
