// This file is auto-generated by @hey-api/openapi-ts

export type GetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type GetResponses = {
  /**
   * API is running successfully. Returns comprehensive service information including health status, environment details, and service availability status.
   */
  200: {
    message: string;
    status: string;
    timestamp: string;
    version: string;
    environment: string;
    cloudflare: {
      region: string | null;
      colo: string | null;
      country: string | null;
      timezone: string | null;
      requestId: string | null;
      asn: string | null;
      httpProtocol: string | null;
    };
    services: {
      database: string;
      realtime: string;
    };
  };
};

export type GetResponse = GetResponses[keyof GetResponses];

export type GetAdminDashboardStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/admin/dashboard/stats';
};

export type GetAdminDashboardStatsErrors = {
  /**
   * Authentication required. Please provide a valid Bearer token.
   */
  401: {
    message: string;
  };
  /**
   * Admin access required. Only users with admin role can access this endpoint.
   */
  403: {
    message: string;
  };
};

export type GetAdminDashboardStatsError =
  GetAdminDashboardStatsErrors[keyof GetAdminDashboardStatsErrors];

export type GetAdminDashboardStatsResponses = {
  /**
   * Successfully retrieved dashboard statistics including user counts, order metrics, and application data.
   */
  200: {
    totalUsers: number;
    totalDrivers: number;
    totalCustomers: number;
    totalAdmins: number;
    totalOrders: number;
    pendingOrders: number;
    completedOrders: number;
    totalDriverApplications: number;
    pendingApplications: number;
  };
};

export type GetAdminDashboardStatsResponse =
  GetAdminDashboardStatsResponses[keyof GetAdminDashboardStatsResponses];

export type GetAdminUsersData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    search?: string;
    sort_by?: string;
    sort_order?: 'asc' | 'desc';
    role?: 'driver' | 'customer' | 'admin';
    country?: string;
    city?: string;
    subscription_status?: boolean | null;
  };
  url: '/admin/users';
};

export type GetAdminUsersErrors = {
  /**
   * Authentication required. Please provide a valid Bearer token.
   */
  401: {
    message: string;
  };
  /**
   * Admin access required. Only users with admin role can access this endpoint.
   */
  403: {
    message: string;
  };
  /**
   * Invalid query parameters. Common issues include: invalid pagination parameters, invalid filter values (role, boolean values), or malformed sort parameters.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type GetAdminUsersError = GetAdminUsersErrors[keyof GetAdminUsersErrors];

export type GetAdminUsersResponses = {
  /**
   * Successfully retrieved paginated and filtered users with administrative details. The response includes pagination metadata and applied filters for navigation.
   */
  200: {
    data: {
      id: number;
      name: string;
      email: string;
      phone: string | null;
      avatar: string | null;
      country: string | null;
      city: string | null;
      role: 'driver' | 'customer' | 'admin';
      stripe_customer_id: string | null;
      subscription_status: boolean;
      ff: boolean;
      createdAt: string | null;
      updatedAt: string | null;
    }[];
    meta: {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
      hasNext: boolean;
      hasPrev: boolean;
    };
  };
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type GetAdminOrdersData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    search?: string;
    sort_by?: string;
    sort_order?: 'asc' | 'desc';
    date_from?: string | null;
    date_to?: string | null;
    price_min?: number | null;
    price_max?: number | null;
    status?: 'pending' | 'accepted' | 'picked_up' | 'in_transit' | 'delivered' | 'cancelled';
    customer_id?: number;
    driver_id?: number;
    pickup_city?: string;
    delivery_city?: string;
  };
  url: '/admin/orders';
};

export type GetAdminOrdersErrors = {
  /**
   * Authentication required. Please provide a valid Bearer token.
   */
  401: {
    message: string;
  };
  /**
   * Admin access required. Only users with admin role can access this endpoint.
   */
  403: {
    message: string;
  };
  /**
   * Invalid query parameters. Common issues include: invalid pagination parameters, invalid filter values (dates, numbers, enum values), or malformed sort parameters.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type GetAdminOrdersError = GetAdminOrdersErrors[keyof GetAdminOrdersErrors];

export type GetAdminOrdersResponses = {
  /**
   * Successfully retrieved paginated and filtered orders in the system. The response includes pagination metadata and applied filters for navigation.
   */
  200: {
    data: {
      id: number;
      customer_id: number;
      driver_id: number | null;
      pickup_address: string;
      delivery_address: string;
      package_description: string;
      package_weight: string | null;
      package_dimensions: string | null;
      price: number;
      status: 'pending' | 'accepted' | 'picked_up' | 'in_transit' | 'delivered' | 'cancelled';
      notes: string | null;
      pickup_time: string | null;
      delivery_time: string | null;
      ff: boolean;
      createdAt: string | null;
      updatedAt: string | null;
    }[];
    meta: {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
      hasNext: boolean;
      hasPrev: boolean;
    };
  };
};

export type GetAdminOrdersResponse = GetAdminOrdersResponses[keyof GetAdminOrdersResponses];

export type GetAdminDriverApplicationsData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    search?: string;
    sort_by?: string;
    sort_order?: 'asc' | 'desc';
    date_from?: string | null;
    date_to?: string | null;
    status?: 'pending' | 'accepted' | 'rejected';
    order_id?: number;
    driver_id?: number;
  };
  url: '/admin/driver-applications';
};

export type GetAdminDriverApplicationsErrors = {
  /**
   * Authentication required. Please provide a valid Bearer token.
   */
  401: {
    message: string;
  };
  /**
   * Admin access required. Only users with admin role can access this endpoint.
   */
  403: {
    message: string;
  };
  /**
   * Invalid query parameters. Common issues include: invalid pagination parameters, invalid filter values (dates, enum values), or malformed sort parameters.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type GetAdminDriverApplicationsError =
  GetAdminDriverApplicationsErrors[keyof GetAdminDriverApplicationsErrors];

export type GetAdminDriverApplicationsResponses = {
  /**
   * Successfully retrieved paginated and filtered driver applications in the system. The response includes pagination metadata and applied filters for navigation.
   */
  200: {
    data: {
      id: number;
      order_id: number;
      driver_id: number;
      status: 'pending' | 'accepted' | 'rejected';
      message: string | null;
      createdAt: string | null;
      updatedAt: string | null;
    }[];
    meta: {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
      hasNext: boolean;
      hasPrev: boolean;
    };
  };
};

export type GetAdminDriverApplicationsResponse =
  GetAdminDriverApplicationsResponses[keyof GetAdminDriverApplicationsResponses];

export type PatchAdminUsersByIdRoleData = {
  /**
   * New role for the user. Must be one of: driver, customer, or admin.
   */
  body?: {
    role: 'driver' | 'customer' | 'admin';
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/admin/users/{id}/role';
};

export type PatchAdminUsersByIdRoleErrors = {
  /**
   * Authentication required. Please provide a valid Bearer token.
   */
  401: {
    message: string;
  };
  /**
   * Admin access required. Only users with admin role can access this endpoint.
   */
  403: {
    message: string;
  };
  /**
   * User not found. Please verify the user ID is correct.
   */
  404: {
    message: string;
  };
  /**
   * Invalid role provided. Role must be one of: driver, customer, or admin.
   */
  422: {
    message: string;
  };
};

export type PatchAdminUsersByIdRoleError =
  PatchAdminUsersByIdRoleErrors[keyof PatchAdminUsersByIdRoleErrors];

export type PatchAdminUsersByIdRoleResponses = {
  /**
   * Successfully updated user role. Returns the updated user information.
   */
  200: {
    id: number;
    name: string;
    email: string;
    phone: string | null;
    avatar: string | null;
    country: string | null;
    city: string | null;
    role: 'driver' | 'customer' | 'admin';
    stripe_customer_id: string | null;
    subscription_status: boolean;
    ff: boolean;
    createdAt: string | null;
    updatedAt: string | null;
  };
};

export type PatchAdminUsersByIdRoleResponse =
  PatchAdminUsersByIdRoleResponses[keyof PatchAdminUsersByIdRoleResponses];

export type PostAdminCleanupData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/admin/cleanup';
};

export type PostAdminCleanupErrors = {
  /**
   * Authentication required. Please provide a valid Bearer token.
   */
  401: {
    message: string;
  };
  /**
   * Admin access required. Only users with admin role can access this endpoint.
   */
  403: {
    message: string;
  };
};

export type PostAdminCleanupError = PostAdminCleanupErrors[keyof PostAdminCleanupErrors];

export type PostAdminCleanupResponses = {
  /**
   * Cleanup completed successfully
   */
  200: {
    message: string;
    deletedTokens?: number;
  };
};

export type PostAdminCleanupResponse = PostAdminCleanupResponses[keyof PostAdminCleanupResponses];

export type PostAuthLoginData = {
  /**
   * User credentials including email and password. Both fields are required for authentication.
   */
  body: {
    email: string;
    password: string;
  };
  path?: never;
  query?: never;
  url: '/auth/login';
};

export type PostAuthLoginErrors = {
  /**
   * Authentication failed. Invalid email or password provided. Please verify your credentials and try again.
   */
  401: {
    message: string;
  };
  /**
   * Invalid login data format. Common issues include: malformed email address or missing required fields.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
  /**
   * Authentication successful. The response includes both access and refresh tokens along with user profile information. Use the access token for API requests and the refresh token to obtain new access tokens.
   */
  200: {
    accessToken: string;
    refreshToken: string;
    user: {
      id: number;
      name: string;
      email: string;
      role: 'driver' | 'customer' | 'admin';
      phone: string | null;
      avatar: string | null;
    };
  };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthRegisterData = {
  /**
   * Complete registration information including name, email, password, role, and optional phone number. Password must be at least 8 characters long.
   */
  body: {
    name: string;
    email: string;
    password: string;
    phone?: string;
    role?: 'driver' | 'customer' | 'admin';
  };
  path?: never;
  query?: never;
  url: '/auth/register';
};

export type PostAuthRegisterErrors = {
  /**
   * Registration failed because the email address is already registered. Please use a different email or try logging in instead.
   */
  409: {
    message: string;
  };
  /**
   * Invalid registration data. Common issues include: weak password (less than 8 characters), invalid email format, missing required fields, or invalid phone number format.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
  /**
   * Account successfully created. The response includes both access and refresh tokens along with the new user's profile information. The user can immediately begin using the system.
   */
  201: {
    accessToken: string;
    refreshToken: string;
    user: {
      id: number;
      name: string;
      email: string;
      role: 'driver' | 'customer' | 'admin';
      phone: string | null;
      avatar: string | null;
    };
  };
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthRefreshData = {
  /**
   * The refresh token obtained during login or registration.
   */
  body: {
    refreshToken: string;
  };
  path?: never;
  query?: never;
  url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
  /**
   * Token refresh failed. The refresh token may be invalid, expired, or revoked. Please log in again to obtain new tokens.
   */
  401: {
    message: string;
  };
  /**
   * Invalid refresh token format. The refresh token must be provided as a string.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
  /**
   * Token refresh successful. A new access token has been generated. The same refresh token is returned and remains valid.
   */
  200: {
    accessToken: string;
    refreshToken: string;
  };
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthLogoutData = {
  /**
   * The refresh token to revoke.
   */
  body: {
    refreshToken: string;
  };
  path?: never;
  query?: never;
  url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
  /**
   * Invalid logout data format. The refresh token must be provided as a string.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
  /**
   * Logout successful. The refresh token has been revoked and can no longer be used.
   */
  200: {
    message: string;
  };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PostAuthLogoutAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/logout-all';
};

export type PostAuthLogoutAllErrors = {
  /**
   * Authentication required. Please provide a valid access token in the Authorization header.
   */
  401: {
    message: string;
  };
};

export type PostAuthLogoutAllError = PostAuthLogoutAllErrors[keyof PostAuthLogoutAllErrors];

export type PostAuthLogoutAllResponses = {
  /**
   * Logout from all devices successful. All refresh tokens for this user have been revoked.
   */
  200: {
    message: string;
  };
};

export type PostAuthLogoutAllResponse =
  PostAuthLogoutAllResponses[keyof PostAuthLogoutAllResponses];

export type GetAuthMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/me';
};

export type GetAuthMeErrors = {
  /**
   * Authentication required or token invalid. Please provide a valid Bearer token in the Authorization header or log in again if your token has expired.
   */
  401: {
    message: string;
  };
};

export type GetAuthMeError = GetAuthMeErrors[keyof GetAuthMeErrors];

export type GetAuthMeResponses = {
  /**
   * Successfully retrieved current user information. The response includes the user's complete profile data including ID, name, email, role, contact information, and avatar.
   */
  200: {
    id: number;
    name: string;
    email: string;
    role: 'driver' | 'customer' | 'admin';
    phone: string | null;
    avatar: string | null;
  };
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type GetUsersData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    search?: string;
    sort_by?: string;
    sort_order?: 'asc' | 'desc';
    role?: 'driver' | 'customer' | 'admin';
    country?: string;
    city?: string;
    subscription_status?: boolean | null;
  };
  url: '/users';
};

export type GetUsersErrors = {
  /**
   * Authentication required. Please provide a valid Bearer token to access user information.
   */
  401: {
    message: string;
  };
  /**
   * Invalid query parameters. Common issues include: invalid pagination parameters (page must be >= 1, limit must be between 1 and 100), invalid filter values (role, boolean values), or malformed sort parameters.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
  /**
   * Successfully retrieved paginated and filtered users. Each user object contains public profile information including name, email, role, and contact details. The response includes pagination metadata and applied filters for navigation.
   */
  200: {
    data: {
      id: number;
      name: string;
      email: string;
      phone: string | null;
      avatar: string | null;
      country: string | null;
      city: string | null;
      role: 'driver' | 'customer' | 'admin';
      stripe_customer_id: string | null;
      subscription_status: boolean;
      ff: boolean;
      createdAt: string | null;
      updatedAt: string | null;
    }[];
    meta: {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
      hasNext: boolean;
      hasPrev: boolean;
    };
  };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersData = {
  /**
   * Complete user information including name, email, password, role, and optional contact details. The password will be securely hashed before storage.
   */
  body: {
    name: string;
    email: string;
    password: string;
    phone?: string | null;
    avatar?: string | null;
    country?: string | null;
    city?: string | null;
    role?: 'driver' | 'customer' | 'admin';
    stripe_customer_id?: string | null;
    subscription_status?: boolean;
    ff?: boolean;
  };
  path?: never;
  query?: never;
  url: '/users';
};

export type PostUsersErrors = {
  /**
   * Invalid request data. Common issues include missing required fields or invalid data formats.
   */
  400: {
    message: string;
  };
  /**
   * Creating admin users is not allowed
   */
  403: {
    message: string;
  };
  /**
   * User creation failed because the email address is already registered in the system.
   */
  409: {
    message: string;
  };
  /**
   * Invalid user data provided. Common issues include: invalid email format, weak password, missing required fields, or duplicate email address.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type PostUsersError = PostUsersErrors[keyof PostUsersErrors];

export type PostUsersResponses = {
  /**
   * User account successfully created. The response contains the new user's profile information excluding the password for security.
   */
  201: {
    id: number;
    name: string;
    email: string;
    phone: string | null;
    avatar: string | null;
    country: string | null;
    city: string | null;
    role: 'driver' | 'customer' | 'admin';
    stripe_customer_id: string | null;
    subscription_status: boolean;
    ff: boolean;
    createdAt: string | null;
    updatedAt: string | null;
  };
};

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export type DeleteUsersByIdData = {
  body?: never;
  path: {
    id: number | null;
  };
  query?: never;
  url: '/users/{id}';
};

export type DeleteUsersByIdErrors = {
  /**
   * User cannot be deleted due to business constraints, such as having active orders or pending applications.
   */
  400: {
    message: string;
  };
  /**
   * Authentication required. Please provide a valid Bearer token to delete user accounts.
   */
  401: {
    message: string;
  };
  /**
   * The specified user was not found in the system. The user may have already been deleted or the ID is incorrect.
   */
  404: {
    message: string;
  };
  /**
   * Invalid user ID format provided in the request parameters. The ID must be a valid integer.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type DeleteUsersByIdError = DeleteUsersByIdErrors[keyof DeleteUsersByIdErrors];

export type DeleteUsersByIdResponses = {
  /**
   * User account successfully deleted. The user and all associated profile data have been permanently removed from the system.
   */
  204: void;
};

export type DeleteUsersByIdResponse = DeleteUsersByIdResponses[keyof DeleteUsersByIdResponses];

export type GetUsersByIdData = {
  body?: never;
  path: {
    id: number | null;
  };
  query?: never;
  url: '/users/{id}';
};

export type GetUsersByIdErrors = {
  /**
   * Authentication required. Please provide a valid Bearer token to access user information.
   */
  401: {
    message: string;
  };
  /**
   * The specified user was not found in the system. Please verify the user ID is correct.
   */
  404: {
    message: string;
  };
  /**
   * Invalid user ID format provided in the request parameters. The ID must be a valid integer.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type GetUsersByIdError = GetUsersByIdErrors[keyof GetUsersByIdErrors];

export type GetUsersByIdResponses = {
  /**
   * Successfully retrieved user information. The response includes the user's public profile data such as name, email, role, contact information, and avatar.
   */
  200: {
    id: number;
    name: string;
    email: string;
    phone: string | null;
    avatar: string | null;
    country: string | null;
    city: string | null;
    role: 'driver' | 'customer' | 'admin';
    stripe_customer_id: string | null;
    subscription_status: boolean;
    ff: boolean;
    createdAt: string | null;
    updatedAt: string | null;
  };
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type PatchUsersByIdData = {
  /**
   * Partial user data containing only the fields to be updated. All fields are optional, allowing for flexible profile updates.
   */
  body: {
    name?: string;
    email?: string;
    password?: string;
    phone?: string | null;
    avatar?: string | null;
    country?: string | null;
    city?: string | null;
    role?: 'driver' | 'customer' | 'admin';
    stripe_customer_id?: string | null;
    subscription_status?: boolean;
    ff?: boolean;
  };
  path: {
    id: number | null;
  };
  query?: never;
  url: '/users/{id}';
};

export type PatchUsersByIdErrors = {
  /**
   * Invalid request data or business rule violation. Common issues include attempting to update restricted fields or invalid data formats.
   */
  400: {
    message: string;
  };
  /**
   * Authentication required. Please provide a valid Bearer token to update user information.
   */
  401: {
    message: string;
  };
  /**
   * The specified user was not found in the system. Please verify the user ID is correct.
   */
  404: {
    message: string;
  };
  /**
   * Update failed due to a conflict, such as trying to change email to one that already exists.
   */
  409: {
    message: string;
  };
  /**
   * Invalid data provided. Common issues include: invalid email format, invalid user ID, or attempting to update restricted fields.
   */
  422:
    | {
        success: boolean;
        error: {
          issues: {
            code: string;
            path: (string | number)[];
            message?: string;
          }[];
          name: string;
        };
      }
    | {
        success: boolean;
        error: {
          issues: {
            code: string;
            path: (string | number)[];
            message?: string;
          }[];
          name: string;
        };
      };
};

export type PatchUsersByIdError = PatchUsersByIdErrors[keyof PatchUsersByIdErrors];

export type PatchUsersByIdResponses = {
  /**
   * User profile successfully updated. The response contains the complete updated user profile with all current information.
   */
  200: {
    id: number;
    name: string;
    email: string;
    phone: string | null;
    avatar: string | null;
    country: string | null;
    city: string | null;
    role: 'driver' | 'customer' | 'admin';
    stripe_customer_id: string | null;
    subscription_status: boolean;
    ff: boolean;
    createdAt: string | null;
    updatedAt: string | null;
  };
};

export type PatchUsersByIdResponse = PatchUsersByIdResponses[keyof PatchUsersByIdResponses];

export type GetOrdersData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    search?: string;
    sort_by?: string;
    sort_order?: 'asc' | 'desc';
    date_from?: string | null;
    date_to?: string | null;
    price_min?: number | null;
    price_max?: number | null;
    status?: 'pending' | 'accepted' | 'picked_up' | 'in_transit' | 'delivered' | 'cancelled';
    customer_id?: number;
    driver_id?: number;
    pickup_city?: string;
    delivery_city?: string;
  };
  url: '/orders';
};

export type GetOrdersErrors = {
  /**
   * Authentication required. Please provide a valid Bearer token to access order information.
   */
  401: {
    message: string;
  };
  /**
   * Access denied. Your account may be inactive or lack sufficient permissions to view orders.
   */
  403: {
    message: string;
  };
  /**
   * Invalid query parameters. Common issues include: invalid pagination parameters (page must be >= 1, limit must be between 1 and 100), invalid filter values (dates, numbers, enum values), or malformed sort parameters.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type GetOrdersError = GetOrdersErrors[keyof GetOrdersErrors];

export type GetOrdersResponses = {
  /**
   * Successfully retrieved paginated and filtered orders based on user role. Customers receive their created orders, drivers receive filtered pending orders (with customer details only for assigned orders), and admins receive all filtered orders in the system. Each order includes complete delivery details, status, and timing information. The response includes pagination metadata and applied filters for navigation.
   */
  200: {
    data: {
      id: number;
      customer_id: number;
      driver_id: number | null;
      pickup_address: string;
      delivery_address: string;
      package_description: string;
      package_weight: string | null;
      package_dimensions: string | null;
      price: number;
      status: 'pending' | 'accepted' | 'picked_up' | 'in_transit' | 'delivered' | 'cancelled';
      notes: string | null;
      pickup_time: string | null;
      delivery_time: string | null;
      ff: boolean;
      createdAt: string | null;
      updatedAt: string | null;
    }[];
    meta: {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
      hasNext: boolean;
      hasPrev: boolean;
    };
  };
};

export type GetOrdersResponse = GetOrdersResponses[keyof GetOrdersResponses];

export type PostOrdersData = {
  /**
   * Complete order information including pickup/delivery addresses, package details, pricing, and optional timing preferences. The order will be automatically assigned to the authenticated customer.
   */
  body: {
    customer_id: number;
    driver_id?: number | null;
    pickup_address: string;
    delivery_address: string;
    package_description: string;
    package_weight?: string | null;
    package_dimensions?: string | null;
    price: number;
    status?: 'pending' | 'accepted' | 'picked_up' | 'in_transit' | 'delivered' | 'cancelled';
    notes?: string | null;
    pickup_time?: string | null;
    delivery_time?: string | null;
    ff?: boolean;
  };
  path?: never;
  query?: never;
  url: '/orders';
};

export type PostOrdersErrors = {
  /**
   * Invalid request data. Common issues include missing required fields, invalid addresses, or malformed data.
   */
  400: {
    message: string;
  };
  /**
   * Authentication required. Please provide a valid Bearer token to create orders.
   */
  401: {
    message: string;
  };
  /**
   * Access denied. Only customers can create delivery orders. Drivers cannot create orders.
   */
  403: {
    message: string;
  };
  /**
   * Invalid order data provided. Common issues include: missing required addresses, invalid pricing, malformed package details, or invalid date formats.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type PostOrdersError = PostOrdersErrors[keyof PostOrdersErrors];

export type PostOrdersResponses = {
  /**
   * Order successfully created and is now available for driver applications. The response includes the complete order details with assigned ID and initial status.
   */
  201: {
    id: number;
    customer_id: number;
    driver_id: number | null;
    pickup_address: string;
    delivery_address: string;
    package_description: string;
    package_weight: string | null;
    package_dimensions: string | null;
    price: number;
    status: 'pending' | 'accepted' | 'picked_up' | 'in_transit' | 'delivered' | 'cancelled';
    notes: string | null;
    pickup_time: string | null;
    delivery_time: string | null;
    ff: boolean;
    createdAt: string | null;
    updatedAt: string | null;
  };
};

export type PostOrdersResponse = PostOrdersResponses[keyof PostOrdersResponses];

export type GetOrdersAvailableData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: '/orders/available';
};

export type GetOrdersAvailableErrors = {
  /**
   * Authentication required. Please provide a valid Bearer token to access available orders
   */
  401: {
    message: string;
  };
  /**
   * Access denied. Your account may be inactive or lack sufficient permissions to view available orders.
   */
  403: {
    message: string;
  };
  /**
   * Invalid pagination parameters. Page must be >= 1 and limit must be between 1 and 100.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type GetOrdersAvailableError = GetOrdersAvailableErrors[keyof GetOrdersAvailableErrors];

export type GetOrdersAvailableResponses = {
  /**
   * Successfully retrieved paginated available orders. Each order includes delivery details, compensation, and timing information to help drivers make informed decisions about which orders to apply for. Customer information is intentionally excluded for privacy reasons and will only be provided after order assignment. The response includes pagination metadata for navigation.
   */
  200: {
    data: {
      id: number;
      pickup_address: string;
      delivery_address: string;
      package_description: string;
      package_weight: string | null;
      package_dimensions: string | null;
      price: number;
      pickup_time: string | null;
      delivery_time: string | null;
      createdAt: string | null;
    }[];
    meta: {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
      hasNext: boolean;
      hasPrev: boolean;
    };
  };
};

export type GetOrdersAvailableResponse =
  GetOrdersAvailableResponses[keyof GetOrdersAvailableResponses];

export type DeleteOrdersByIdData = {
  body?: never;
  path: {
    id: number | null;
  };
  query?: never;
  url: '/orders/{id}';
};

export type DeleteOrdersByIdErrors = {
  /**
   * Order cannot be deleted due to business constraints, such as having an assigned driver or being in progress.
   */
  400: {
    message: string;
  };
  /**
   * Authentication required. Please provide a valid Bearer token to delete orders.
   */
  401: {
    message: string;
  };
  /**
   * Access denied. Only customers can delete their own orders, and admins can delete any order. Orders in progress cannot be deleted.
   */
  403: {
    message: string;
  };
  /**
   * The specified order was not found in the system. The order may have already been deleted or the ID is incorrect.
   */
  404: {
    message: string;
  };
  /**
   * Invalid order ID format provided in the request parameters. The ID must be a valid integer.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type DeleteOrdersByIdError = DeleteOrdersByIdErrors[keyof DeleteOrdersByIdErrors];

export type DeleteOrdersByIdResponses = {
  /**
   * Order successfully cancelled/deleted. The order has been removed from the system and is no longer available for driver applications.
   */
  204: void;
};

export type DeleteOrdersByIdResponse = DeleteOrdersByIdResponses[keyof DeleteOrdersByIdResponses];

export type GetOrdersByIdData = {
  body?: never;
  path: {
    id: number | null;
  };
  query?: never;
  url: '/orders/{id}';
};

export type GetOrdersByIdErrors = {
  /**
   * Authentication required. Please provide a valid Bearer token to access order information.
   */
  401: {
    message: string;
  };
  /**
   * Access denied. You don't have permission to view this order. Users can only access their own orders, orders assigned to them, or pending orders if they're drivers.
   */
  403: {
    message: string;
  };
  /**
   * The specified order was not found in the system. Please verify the order ID is correct.
   */
  404: {
    message: string;
  };
  /**
   * Invalid order ID format provided in the request parameters. The ID must be a valid integer.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type GetOrdersByIdError = GetOrdersByIdErrors[keyof GetOrdersByIdErrors];

export type GetOrdersByIdResponses = {
  /**
   * Successfully retrieved order information. The response includes complete delivery details, current status, customer information (if accessible based on user role and assignment), assigned driver (if any), and all tracking data.
   */
  200: {
    id: number;
    customer_id: number;
    driver_id: number | null;
    pickup_address: string;
    delivery_address: string;
    package_description: string;
    package_weight: string | null;
    package_dimensions: string | null;
    price: number;
    status: 'pending' | 'accepted' | 'picked_up' | 'in_transit' | 'delivered' | 'cancelled';
    notes: string | null;
    pickup_time: string | null;
    delivery_time: string | null;
    ff: boolean;
    createdAt: string | null;
    updatedAt: string | null;
  };
};

export type GetOrdersByIdResponse = GetOrdersByIdResponses[keyof GetOrdersByIdResponses];

export type PatchOrdersByIdData = {
  /**
   * Partial order data containing only the fields to be updated. Available fields depend on user role and order status. Customers can modify delivery details, drivers can update status and tracking.
   */
  body: {
    customer_id?: number;
    driver_id?: number | null;
    pickup_address?: string;
    delivery_address?: string;
    package_description?: string;
    package_weight?: string | null;
    package_dimensions?: string | null;
    price?: number;
    status?: 'pending' | 'accepted' | 'picked_up' | 'in_transit' | 'delivered' | 'cancelled';
    notes?: string | null;
    pickup_time?: string | null;
    delivery_time?: string | null;
    ff?: boolean;
  };
  path: {
    id: number | null;
  };
  query?: never;
  url: '/orders/{id}';
};

export type PatchOrdersByIdErrors = {
  /**
   * Invalid request data or business rule violation. Common issues include invalid status transitions, updating completed orders, or malformed data.
   */
  400: {
    message: string;
  };
  /**
   * Authentication required. Please provide a valid Bearer token to update orders.
   */
  401: {
    message: string;
  };
  /**
   * Access denied. You don't have permission to modify this order, or the order status doesn't allow updates.
   */
  403: {
    message: string;
  };
  /**
   * The specified order was not found in the system. Please verify the order ID is correct.
   */
  404: {
    message: string;
  };
  /**
   * Update failed due to a conflict, such as the order being modified by another user or having an incompatible status change.
   */
  409: {
    message: string;
  };
  /**
   * Invalid data provided. Common issues include: invalid order ID, restricted field updates, invalid status transitions, or malformed data.
   */
  422:
    | {
        success: boolean;
        error: {
          issues: {
            code: string;
            path: (string | number)[];
            message?: string;
          }[];
          name: string;
        };
      }
    | {
        success: boolean;
        error: {
          issues: {
            code: string;
            path: (string | number)[];
            message?: string;
          }[];
          name: string;
        };
      };
};

export type PatchOrdersByIdError = PatchOrdersByIdErrors[keyof PatchOrdersByIdErrors];

export type PatchOrdersByIdResponses = {
  /**
   * Order successfully updated. The response contains the complete updated order information with all current details and status.
   */
  200: {
    id: number;
    customer_id: number;
    driver_id: number | null;
    pickup_address: string;
    delivery_address: string;
    package_description: string;
    package_weight: string | null;
    package_dimensions: string | null;
    price: number;
    status: 'pending' | 'accepted' | 'picked_up' | 'in_transit' | 'delivered' | 'cancelled';
    notes: string | null;
    pickup_time: string | null;
    delivery_time: string | null;
    ff: boolean;
    createdAt: string | null;
    updatedAt: string | null;
  };
};

export type PatchOrdersByIdResponse = PatchOrdersByIdResponses[keyof PatchOrdersByIdResponses];

export type GetOrdersByIdApplicationsData = {
  body?: never;
  path: {
    id: number | null;
  };
  query?: {
    page?: number;
    limit?: number;
    search?: string;
    sort_by?: string;
    sort_order?: 'asc' | 'desc';
    date_from?: string | null;
    date_to?: string | null;
    status?: 'pending' | 'accepted' | 'rejected';
    order_id?: number;
    driver_id?: number;
  };
  url: '/orders/{id}/applications';
};

export type GetOrdersByIdApplicationsErrors = {
  /**
   * Authentication required. Please provide a valid Bearer token
   */
  401: {
    message: string;
  };
  /**
   * Access denied. You don't have permission to view applications for this order.
   */
  403: {
    message: string;
  };
  /**
   * The specified order was not found in the system
   */
  404: {
    message: string;
  };
  /**
   * Invalid order ID format or query parameters. Common issues include: invalid pagination parameters, invalid filter values (dates, enum values), or malformed sort parameters.
   */
  422:
    | {
        success: boolean;
        error: {
          issues: {
            code: string;
            path: (string | number)[];
            message?: string;
          }[];
          name: string;
        };
      }
    | {
        success: boolean;
        error: {
          issues: {
            code: string;
            path: (string | number)[];
            message?: string;
          }[];
          name: string;
        };
      };
};

export type GetOrdersByIdApplicationsError =
  GetOrdersByIdApplicationsErrors[keyof GetOrdersByIdApplicationsErrors];

export type GetOrdersByIdApplicationsResponses = {
  /**
   * Successfully retrieved paginated and filtered driver applications for the order. Each application includes the driver's profile information to help with selection decisions. The response includes pagination metadata and applied filters for navigation.
   */
  200: {
    data: {
      id: number;
      order_id: number;
      driver_id: number;
      status: 'pending' | 'accepted' | 'rejected';
      message: string | null;
      createdAt: string | null;
      updatedAt: string | null;
      driver: {
        id: number;
        name: string;
        email: string;
        phone: string | null;
        avatar: string | null;
      };
    }[];
    meta: {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
      hasNext: boolean;
      hasPrev: boolean;
    };
  };
};

export type GetOrdersByIdApplicationsResponse =
  GetOrdersByIdApplicationsResponses[keyof GetOrdersByIdApplicationsResponses];

export type GetDriversByIdApplicationsData = {
  body?: never;
  path: {
    id: number | null;
  };
  query?: {
    page?: number;
    limit?: number;
    search?: string;
    sort_by?: string;
    sort_order?: 'asc' | 'desc';
    date_from?: string | null;
    date_to?: string | null;
    status?: 'pending' | 'accepted' | 'rejected';
    order_id?: number;
    driver_id?: number;
  };
  url: '/drivers/{id}/applications';
};

export type GetDriversByIdApplicationsErrors = {
  /**
   * Authentication required. Please provide a valid Bearer token
   */
  401: {
    message: string;
  };
  /**
   * Access denied. You don't have permission to view applications for this driver.
   */
  403: {
    message: string;
  };
  /**
   * The specified driver was not found in the system
   */
  404: {
    message: string;
  };
  /**
   * Invalid driver ID format or query parameters. Common issues include: invalid pagination parameters, invalid filter values (dates, enum values), or malformed sort parameters.
   */
  422:
    | {
        success: boolean;
        error: {
          issues: {
            code: string;
            path: (string | number)[];
            message?: string;
          }[];
          name: string;
        };
      }
    | {
        success: boolean;
        error: {
          issues: {
            code: string;
            path: (string | number)[];
            message?: string;
          }[];
          name: string;
        };
      };
};

export type GetDriversByIdApplicationsError =
  GetDriversByIdApplicationsErrors[keyof GetDriversByIdApplicationsErrors];

export type GetDriversByIdApplicationsResponses = {
  /**
   * Successfully retrieved paginated and filtered applications by the driver. Each application includes detailed order information and current status to help drivers track their work progress. The response includes pagination metadata and applied filters for navigation.
   */
  200: {
    data: {
      id: number;
      order_id: number;
      driver_id: number;
      status: 'pending' | 'accepted' | 'rejected';
      message: string | null;
      createdAt: string | null;
      updatedAt: string | null;
      order: {
        id: number;
        pickup_address: string;
        delivery_address: string;
        package_description: string;
        price: number;
        status: 'pending' | 'accepted' | 'picked_up' | 'in_transit' | 'delivered' | 'cancelled';
        createdAt: string | null;
      };
    }[];
    meta: {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
      hasNext: boolean;
      hasPrev: boolean;
    };
  };
};

export type GetDriversByIdApplicationsResponse =
  GetDriversByIdApplicationsResponses[keyof GetDriversByIdApplicationsResponses];

export type PostDriverApplicationsData = {
  /**
   * Application details including driver ID and order ID. The system will automatically set the application status to 'pending' and record the submission timestamp.
   */
  body: {
    order_id: number;
    driver_id: number;
    status?: 'pending' | 'accepted' | 'rejected';
    message?: string | null;
  };
  path?: never;
  query?: never;
  url: '/driver-applications';
};

export type PostDriverApplicationsErrors = {
  /**
   * Application could not be created. Common reasons include: driver has already applied for this order, order is no longer available, or order has already been assigned to another driver.
   */
  400: {
    message: string;
  };
  /**
   * Authentication required. Please provide a valid Bearer token
   */
  401: {
    message: string;
  };
  /**
   * Access denied. Only drivers can submit applications for orders.
   */
  403: {
    message: string;
  };
  /**
   * The specified order was not found or is no longer available for applications.
   */
  404: {
    message: string;
  };
  /**
   * Application already exists for this driver and order combination.
   */
  409: {
    message: string;
  };
  /**
   * Invalid application data provided. Please check that all required fields are present and properly formatted.
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type PostDriverApplicationsError =
  PostDriverApplicationsErrors[keyof PostDriverApplicationsErrors];

export type PostDriverApplicationsResponses = {
  /**
   * Application successfully created and submitted for review. The order owner will be notified of the new application.
   */
  201: {
    id: number;
    order_id: number;
    driver_id: number;
    status: 'pending' | 'accepted' | 'rejected';
    message: string | null;
    createdAt: string | null;
    updatedAt: string | null;
  };
};

export type PostDriverApplicationsResponse =
  PostDriverApplicationsResponses[keyof PostDriverApplicationsResponses];

export type PatchDriverApplicationsByIdData = {
  /**
   * New status for the application. 'accepted' assigns the driver to the order, 'rejected' declines the application but keeps it for record-keeping.
   */
  body: {
    status: 'accepted' | 'rejected';
  };
  path: {
    id: number | null;
  };
  query?: never;
  url: '/driver-applications/{id}';
};

export type PatchDriverApplicationsByIdErrors = {
  /**
   * Status update failed. Common reasons include: application has already been processed, order is no longer available, or insufficient permissions to modify this application.
   */
  400: {
    message: string;
  };
  /**
   * Authentication required. Please provide a valid Bearer token
   */
  401: {
    message: string;
  };
  /**
   * Access denied. Only order owners can update application status.
   */
  403: {
    message: string;
  };
  /**
   * The specified application was not found in the system
   */
  404: {
    message: string;
  };
  /**
   * Status update failed due to a conflict, such as the application being modified by another user or the order already being assigned.
   */
  409: {
    message: string;
  };
  /**
   * Invalid application ID format or status value provided in the request
   */
  422: {
    success: boolean;
    error: {
      issues: {
        code: string;
        path: (string | number)[];
        message?: string;
      }[];
      name: string;
    };
  };
};

export type PatchDriverApplicationsByIdError =
  PatchDriverApplicationsByIdErrors[keyof PatchDriverApplicationsByIdErrors];

export type PatchDriverApplicationsByIdResponses = {
  /**
   * Application status successfully updated. If accepted, the driver has been assigned to the order and will be notified. If rejected, the driver will be informed and can apply for other available orders.
   */
  200: {
    id: number;
    order_id: number;
    driver_id: number;
    status: 'pending' | 'accepted' | 'rejected';
    message: string | null;
    createdAt: string | null;
    updatedAt: string | null;
  };
};

export type PatchDriverApplicationsByIdResponse =
  PatchDriverApplicationsByIdResponses[keyof PatchDriverApplicationsByIdResponses];

export type GetRealtimeWebsocketData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/realtime/websocket';
};

export type GetRealtimeWebsocketErrors = {
  /**
   * Bad request - missing required parameters or invalid WebSocket upgrade
   */
  400: {
    error: string;
    message?: string;
  };
  /**
   * Authentication required
   */
  401: {
    message: string;
  };
};

export type GetRealtimeWebsocketError =
  GetRealtimeWebsocketErrors[keyof GetRealtimeWebsocketErrors];

export type PostRealtimeBroadcastData = {
  body?: {
    type:
      | 'order_created'
      | 'order_updated'
      | 'order_status_changed'
      | 'driver_assigned'
      | 'location_update'
      | 'application_created'
      | 'application_updated';
    data: {
      [key: string]: unknown;
    };
    orderId?: string;
    userId?: string;
    targetUsers?: string[];
  };
  path?: never;
  query?: never;
  url: '/realtime/broadcast';
};

export type PostRealtimeBroadcastErrors = {
  /**
   * Authentication required
   */
  401: {
    message: string;
  };
  /**
   * Insufficient permissions to broadcast events
   */
  403: {
    message: string;
  };
  /**
   * Internal server error
   */
  500: {
    error: string;
  };
};

export type PostRealtimeBroadcastError =
  PostRealtimeBroadcastErrors[keyof PostRealtimeBroadcastErrors];

export type PostRealtimeBroadcastResponses = {
  /**
   * Event broadcasted successfully
   */
  200: {
    success: boolean;
    message: string;
  };
};

export type PostRealtimeBroadcastResponse =
  PostRealtimeBroadcastResponses[keyof PostRealtimeBroadcastResponses];

export type GetRealtimeConnectionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/realtime/connections';
};

export type GetRealtimeConnectionsErrors = {
  /**
   * Authentication required
   */
  401: {
    message: string;
  };
  /**
   * Internal server error
   */
  500: {
    error: string;
  };
};

export type GetRealtimeConnectionsError =
  GetRealtimeConnectionsErrors[keyof GetRealtimeConnectionsErrors];

export type GetRealtimeConnectionsResponses = {
  /**
   * Active connections retrieved
   */
  200: {
    count: number;
    connections: {
      userId: string;
      userRole: 'admin' | 'driver' | 'customer';
      connectedAt: number;
      lastActivity: number;
    }[];
  };
};

export type GetRealtimeConnectionsResponse =
  GetRealtimeConnectionsResponses[keyof GetRealtimeConnectionsResponses];

export type GetRealtimeHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/realtime/health';
};

export type GetRealtimeHealthErrors = {
  /**
   * Internal server error
   */
  500: {
    error: string;
  };
};

export type GetRealtimeHealthError = GetRealtimeHealthErrors[keyof GetRealtimeHealthErrors];

export type GetRealtimeHealthResponses = {
  /**
   * Service is healthy
   */
  200: {
    status: string;
    timestamp: number;
  };
};

export type GetRealtimeHealthResponse =
  GetRealtimeHealthResponses[keyof GetRealtimeHealthResponses];

export type ClientOptions = {
  baseUrl: 'https://ro-cargo-api.dreambigg.workers.dev' | (string & {});
};
